version: "3.5"

networks:
  debian-net:
    name: debian-net
    driver: bridge
    ipam:
      config:
        - subnet: 12.0.0.0/8

services:
  debianserver:
    build: debian-custom
    image: villcabo/debian-server-ssh
    restart: unless-stopped
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      debian-net:
        ipv4_address: 12.0.0.13